ecommerse/ecommerceproject/cart/urls.py
from django.urls import path
from .import views



app_name='cart'

urlpatterns = [
    path('',views.cart_detail,name='cart_detail'),
    path('add/<int:product_id>/',views.add_cart,name='add_cart'),
    path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
    path('full_remove/<int:product_id>/',views.full_remove,name='full_remove'),
]

ecommerse/ecommerceproject/ecommerceproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/',include("shop.urls")),
    path('search_app/',include("search_app.urls")),
    path('cart/',include('cart.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

ecommerse/ecommerceproject/search_app/urls.py
from django.urls import path
from .import views



app_name='search_app'

urlpatterns = [
    path(' ',views.SearchResult,name='SearchResult'),
]

ecommerse/ecommerceproject/shop/urls.py
from django.urls import path
from .import views



app_name='shop'
urlpatterns = [
    # path('', views.index, name='index'),
    path('',views.allProdCat,name='allProdCat'),
    path('<slug:c_slug>/',views.allProdCat, name='product_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/',views.proDetail, name='proCatdetail'),

]

ecommerse/ecommerceproject/cart/models.py
from django.db import models
from shop.models import Product

# Create your models here.
class Cart(models.Model):
    cart_id=models.CharField(max_length=250,blank=True)
    date_added=models.DateField(auto_now_add=True)
    class Meta:
        db_table ='cart'
        ordering = ['date_added']

    def __str__(self):
        return (self.cart_id)

class CartItem(models.Model):
    product= models.ForeignKey(Product, on_delete=models.CASCADE)
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity= models.IntegerField()
    active=models.BooleanField(default=True)

    class Meta:
        db_table='CartItem'

    def sub_total(self):
        return self.product.price*self.quantity

    def __str__(self):
        return (self.product)

ecommerse/ecommerceproject/search_app/models.py
from django.db import models


# Create your models here.

ecommerse/ecommerceproject/shop/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Category(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250, unique=True)
    description=models.TextField(blank=True)
    image=models.ImageField(upload_to='category',blank=True)

    class Meta:
        ordering=('name',)
        verbose_name= 'category'
        verbose_name_plural= 'categories'

    def get_url(self):
        return reverse('shop:product_by_category',args=[self.slug])

    def __str__(self):
        return self.name

class Product(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    description=models.TextField(blank=True)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    image=models.ImageField(upload_to='product',blank=True)
    stock=models.IntegerField()
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)

    def get_url(self):
        return reverse('shop:proCatdetail', args=[self.category.slug, self.slug])

    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'



    def __str__(self):
        return self.name

ecommerse/ecommerceproject/cart/views.py
from django.shortcuts import render,redirect
from shop.models import Product
from .models import Cart, CartItem
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import get_object_or_404


# Create your views here.

def _cart_id(request):
    cart=request.session.session_key
    if not cart:
        cart=request.session.create()
    return cart

def add_cart(request,product_id):
    product=Product.objects.get(id=product_id)
    try:
        cart= Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart= Cart.objects.create(cart_id=_cart_id(request))

    cart.save()


    try:
        cart_item=CartItem.objects.get(product=product,cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity +=1
        cart_item.save()

    except CartItem.DoesNotExist:
        cart_item=CartItem.objects.create(product=product,quantity=1,cart=cart)

        cart_item.save()

    return redirect('cart:cart_detail')

def cart_detail(request,total=0,counter=0,cart_items=None):

    try:
        cart= Cart.objects.get (cart_id= _cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart,active=True)

        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity

    except ObjectDoesNotExist:
        pass

    return render(request, 'cart.html', dict(cart_items=cart_items,total=total,counter=counter))
# detele quantity of items one by one
def cart_remove(request, product_id):
    cart=Cart.objects.get(cart_id= _cart_id(request))
    product = Product.objects.get(id=product_id)
    product = get_object_or_404(Product,id=product_id)
    cart_item =CartItem.objects.get(product=product, cart=cart)

    if cart_item.quantity > 1 :
        cart_item.quantity -= 1
        cart_item.save()

    else:
        cart_item.delete()
    return redirect('cart:cart_detail')

# delete item completely
def full_remove(request, product_id):
    cart = Cart.objects.get(cart_id= _cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    cart_item.delete()

    return redirect('cart:cart_detail')

ecommerse/ecommerceproject/search_app/views.py
from django.shortcuts import render
from shop.models import Product
from django.db.models import Q

# from django import forms
# Create your views here.


def SearchResult(request):
    products=None
    query=None
    if 'q' in request.GET:
        query=request.GET.get('q')
        products = Product.objects.all().filter(Q(name__contains=query)|Q(description__contains=query))
        return render(request, 'search.html',{'query':query,'products':products})







# def SearchResult(request):
#     if request.method == "POST":
#         query_name = request.POST.get('name', None)
#         if query_name:
#             results = Product.objects.filter(name__contains=query_name)
#             return render(request, 'search.html', {"results":results})
#     return render(request, 'search.html')

ecommerse/ecommerceproject/shop/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from .models import Category,Product
from django.core .paginator import Paginator, EmptyPage, InvalidPage

# Create your views here.
# def index(request):
#     return HttpResponse("Hello and welcome!")

#to see the available products listed

def allProdCat(request,c_slug=None):
    c_page=None
    products_list=None
    if c_slug!=None:
        c_page=get_object_or_404(Category,slug=c_slug)
        products_list=Product.objects.all().filter(category=c_page,available=True)
    else:
        products_list=Product.objects.all().filter(available=True)

        # paginator code
        paginator= Paginator(products_list,6)
        try:
            page=int(request.GET.get('page','1'))
        except:
            page=1

        try:
            products=paginator.page(page)
        except (EmptyPage,InvalidPage):
            products=paginator.page(paginator.num_pages)

    return render(request,"cat.html",{'category':c_page,'products':products})

# to view product and add to cart

def proDetail(request, c_slug, product_slug):
    try:
        product = Product.objects.get(category__slug=c_slug,slug=product_slug)
    except Exception as e:
        raise e
    return render(request,'product.html',{'product':product})

ecommerse/ecommerceproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
     <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'css/custom.css' %}" rel="stylesheet">
        <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    <meta name="description" content="{% block metadescription %} {% endblock %}">
    <title>{% block title %} {% endblock %}</title>
</head>
<body >
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@100&display=swap" rel="stylesheet">
<div class ="container">
  {% include 'header.html' %}
  {% include 'navbar.html' %}
  {% block content %}
    {% endblock %}
</div>
{% include 'footer.html' %}
    <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
 <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
            integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
            crossorigin="anonymous"></script>
</body>
</html>

ecommerse/ecommerceproject/templates/cart.html
{% extends 'base.html' %}
{% load static %}

{% block metadescription %}
Thanking for shopping with us!! Do review your cart before proceeding to payment.
{% endblock %}

{% block title %}
Your Cart
{% endblock %}

{% block content %}
<!--if no items in the cart-->
<div>
{% if not cart_items %}
    <div class="text-center"><br>
        <h1 class="text-center my_title">Your cart is empty</h1>
        <p class="text-center">Please click <a href="{% url 'shop:allProdCat' %}">HERE</a>to continue shopping</p>
    </div>
{% else %}
<!--If the cart is not empty-->
    <div class="text-center">
        <h1 class="text-center my_title">Your Shopping Cart!</h1><br>
    </div>
{% endif %}
</div>

<!--Display the items in cart-->
<div>
    <div class="row mx_auto">
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
            <table class="table my_custom_table">
                <thead class="my_custom_thead">
                <tr>
                    <th colspan="5">
                        Your Items
                    </th>
                </tr>
                </thead>
                <tbody>
                {% for cart_item in cart_items %}
                <tr>
                    <td>
                        <a href="cart_item.product.get_absolute_url">
                            <img src="{{cart_item.product.image.url}}" width="100px" height="100 px"
                            alt="" class="float-left rounded custom_image"></a>
                    </td>

                    <td class="text-left">
                        {{cart_item.product.name}}
                        <br>
                        SKU: {{cart_item.product.id}}
                        <br>
                        Price: $ {{cart_item.product.price}}
                        <br>
                        Qty: {{cart_item.quantity}}
                        <br>
                    </td>

<!--to show total amount                    -->
                    <td>${{cart_item.sub_total}}</td>
<!--To verify if the stock is there before adding the items                    -->
       {% if cart_item.quantity < cart_item.product.stock %}
       <td>
        <a href ="{% url 'cart:add_cart' cart_item.product.id %}" class="custom_a"><i class="fa fa-plus custom_icon"></i></a>
        <a href ="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a" ><i class="fa fa-minus custom_icon"></i></a>
        <a href ="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_a" ><i class="fa fa-trash custom_icon"></i></a>
        </td>
         {% else %}
         <td>
         <a href ="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a" ><i class="fa fa-minus custom_icon"></i></a>
         <a href ="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_a" ><i class="fa fa-trash custom_icon"></i></a>
         </td>
         {% endif %}
         </tr>
         {% endfor %}
         </tbody>
         </table>
        </div><br>

            <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
            <table class="table my_custom_table">
            <thead class="my_custom_thead">
            <tr>
            <th colspan="5">CHECK OUT</th>
            </tr>
            </thead>
            <tbody>
                <tr>
                    <td class="text-left">
                    Please don't forget to review your items before proceeding to payment.
                    </td>
                </tr>
            <tr>
                <td class="text-left">Your Total Bill:<strong>{{total}}</strong></td>
            </tr>
            </tbody>

            </table>

            <div class="mx_auto">
                <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
                <a href="{% url 'shop:allProdCat' %}" class="btn btn-success btn-block my_custom_button">Continue Shopping</a>
            </div>
<br>
            </div>

 </div>
        </div>
    </div>
{% endblock %}

ecommerse/ecommerceproject/templates/cat.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


  {% block metadescription %}
    {% if category %}
      {{category.description|truncatewords:150}}
    {% else %}
      Hello Welcome's you!!!
    {% endif %}
  {% endblock %}

  {% block title %}
    {% if category %}
      {{category.name}} Hello online store welcome's you!
    {% else %}
        Our collections now includes womens,mens and kids dresses
  {% endif %}
  {% endblock %}

  {% block contents %}
{% if category %}
<div>
  <div class="row my_row_class">
    <div class="mx_auto">
    <p>
      <a href="{% url 'shop:allProdCat' %}">Our collections</a>
    </p>
      </div>
  </div>
</div>
{% endif %}
<div class="mx_auto">
{% if category %}
<img class="my_image" src ="{{category.image.url}}" height="400px" width="1250px" alt="{{category.name}}">
</div><br>
<div>
  <h1 class="text-center my_title">{{category.name}}</h1>
  <p class="text-justify">{{category.description}}</p>
</div>
{% else %}
<div>
   <img class="my_image my_image_padding" src="{% static 'img/banner.png' %}" alt ="Our Products" width="1150 px" height="300 px">
</div><br>
<div>
  <h1 class="text-center my_title">Latest updates in the world of fashion</h1>
  <p class="text-justify"> The changing of the seasons from winter to spring is a most exciting time—especially sartorially. In with lighter layers, dresses, and a sense of freedom; out with heavy outerwear, knits, and boots. When it comes to the spring 2023 trends, there’s a lot to look forward to. As noted by Vogue Runway’s trend report, the collections reflected many moods: from soft and undone (read draped jersey, distressed fabrics, and other touchable textures) to utilitarian preparedness (think well-pocketed garments) and a streamlined minimalism (see smart tailoring and even smarter button-up shirting). Our editors have already begun to gravitate to a handful of these, eager to transition to the spring wardrobe. </p>
</div>
{% endif %}

<div class="container-fluid">
  <div class="row mx_auto">
    {% for product in products.object_list %}
    <div class="my_bottom_margin col 9 col-sm-12 col-md-2 col-lg-2 offset-md-0">
      <div class="card-text-center" style="min-width=18rem;">
        <a href="{{product.get_url}}">
                <img class="card-img my_image" src="{{product.image.url}}" alt="{{product.name}}"></a>
      </div>
        <div class="my_bottom_margin col 9 col-sm-12 col-md-2 col-lg-2 offset-md-0">
      <div class="card-text-center" style="min-width=18rem;">
        <a href="{{product.get_url}}">
                <img class="card-img my_image" src="{{product.image.url}}" alt="{{product.name}}"></a>
      </div>
            <div class="my_bottom_margin col 9 col-sm-12 col-md-2 col-lg-2 offset-md-0">
      <div class="card-text-center" style="min-width=18rem;">
        <a href="{{product.get_url}}">
                <img class="card-img my_image" src="{{product.image.url}}" alt="{{product.name}}"></a>
      </div>

      <div class="card-body">
      <h4 class="card_body">{{product.name}}</h4>
      <h4 class="card_body">${{product.price}}</h4>
      </div>
      </div>
      </div>
    </div>
    {% endfor %}
  </div>

<!--  to display page no as 1,2...-->
  <div class="mx_auto">
    {% if products.paginator.num_pages > 1 %}
    <hr>
    <div class="text-center">
      {% for pg in products.paginator.page_range %}
      <a href="?page={{pg}}" class="btn btn-light btn-sm" {% if products.number == pg %} active {% endif %}">{{pg}}</a>
      {% endfor %}

    </div>
     {% endif %}
  </div>
  <br>
</div>
{% endblock %}

{% endblock %}

ecommerse/ecommerceproject/templates/footer.html
<div class="footer navbar-fixed-bottom my-footer">
    <p class="text-center"> <br>
        @Copy; Hello marketing solutions pvt ltd. All rights reserved.
    </p>
</div>

ecommerse/ecommerceproject/templates/header.html
{% load static %}

<header>

  <center>
    <a href ="{% url 'shop:allProdCat' %}"></a>
    <img src="{% static 'img/logo.png' %}" alt="logo_image" width="250 px" height="150 px">
  </center>

</header>

ecommerse/ecommerceproject/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'shop:allProdCat' %}">Home<span class="sr-only">(current)</span></a>
      </li>
      <!-- dropdowm button for shopping categories -->
<div class="btn-group">
  <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
    SHOP HERE
  </button>
  <div class="dropdown-menu">
    <a class="dropdown-item" href="{% url 'shop:allProdCat' %}"> All Products </a>
    {% for cat in links %}
    <a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a>
    {% endfor %}

  </div>
</div>
       <li class="nav-item">
        <a class="nav-link disabled">
          <i class="fa-thin fa-cart-arrow-down"></i></a>
      </li>
    </ul>
  </div>
<!--  <div>-->
<!--      <li class="nav-item dropdown {% if 'shop' in request.path %} active {% endif %}">-->
<!--        <a class="nav-link dropdown-toggle" href="{% url 'shop:allProdCat' %}" role="button"  data-bs-toggle="dropdown" aria-expanded="false">-->
<!--         SHOP HERE</a>-->
<!--        <div class="dropdown-menu">-->
<!--          <a class="dropdown-item" href="{% url 'shop:allProdCat' %}">All Products</a>-->
<!--            {% for cat in links %}-->
<!--          <a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a>-->
<!--            {% endfor %}-->
<!--            </div>-->
<!--      </li>-->
<!--  </div>-->
<div>
{% if item_count > 0 %}
    <li class="nav_item" >
        <a class="nav_link" href="{% url 'cart:cart_detail' %}">
          <i class="fa-solid fa-cart-shopping"></i>({{item_count}})</a>
    </li>
{% endif %}
</div>




<!--Searching items from the lists-->
<div>
       <form class="d-flex" action="{% url 'search_app:SearchResult' %}" method="get">
          {% csrf_token %}
        <input class="form-control mr-sm-2" type="search" placeholder="Search here" name="q" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="fa-solid fa-magnifying-glass"></i></button>
    </form>
</div>
</nav>


<!--<{% if 'shop' in request.path %} active {% endif %}">-->


<!--<nav>-->
<!--&lt;!&ndash;  <ul>&ndash;&gt;-->
<!--&lt;!&ndash;    <li><a href ="{% url 'shop:allProdCat' %}"> All Products </a></li>&ndash;&gt;-->
<!--&lt;!&ndash;&lt;!&ndash;To show all the links&ndash;&gt;&ndash;&gt;-->
<!--&lt;!&ndash;    {% for cat in links %}&ndash;&gt;-->
<!--&lt;!&ndash;    <li><a href="{{cat.get_url}}">{{cat.name}}</a></li>&ndash;&gt;-->
<!--&lt;!&ndash;    {% endfor %}&ndash;&gt;-->

<!--    <li><i class="fa-regular fa-cart-shopping"></i></li>-->

<!--  </ul>-->
<!--</nav>-->

ecommerse/ecommerceproject/templates/product.html
{% extends 'base.html' %}
{% load static %}
font-family: 'Roboto Slab', serif;

{% block meta %}
    {{product.description|truncatewords:150}}
{% endblock %}

{% block title %}
    {% if category %}
    {{product.name}} Thankyou for choosing us!!!
    {% endif %}
{% endblock %}

{% block content %}
<div class="row my_prod_row_class">
  <div class="mx_auto">
    <p>
      <a href="{% url 'shop:allProdCat' %}">Home</a>|<a href ="{{product.category.get_url}}">{{product.category}}</a>|{{product.name}}
    </p>
  </div>
</div>
<div class="container">
<br>
<div class="row">
    <div class=" col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <div style="min-width:18rem">
            <img src="{{product.image.url}}" height="400px" width="300 px" alt="{{product.name}}">

        </div>
    </div>

        <div class="col-12 col-sm-12 col-md-12 col-lg-6">
            <div>
            <h1 class="my_prod_title">{{product.name}}</h1>
            <p>${{product.price}}</p>
            <p class="my_title">Product Description</p>
            <p class="text-justify my_prod_text">{{product.description}}</p>
            {% if product.stock <= 0 %}
            <p  class="text-justify my_prod_text">Out of Stock</p>
            {% else %}
            <a class="btn btn-success" href="{% url 'cart:add_cart' product.id %}">Add to cart</a>
            {% endif %}
        </div>
    </div>
    </div>
</div>
 <br>

{% endblock %}

ecommerse/ecommerceproject/templates/search.html
{% extends 'base.html' %}
{% load static %}

{% block metadescription %}
We have a wide range of products waiting for you!!!
{% endblock %}

{% block title %}
Search here
{% endblock %}

{% block content %}
<div>
    <p class="text-center my_search_text">You have searched for: <br>"{{query}}"</p>
    <div class="container">
          <div class="row mx_auto">
                 {% for product in products %}
                      <div class=" col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <div style="min-width:18rem">
            <img src="{{product.image.url}}" height="300px" width="200 px" alt="{{product.name}}">

          <div class="card-body">
             <h4 class="card_body">{{product.name}}</h4>
             <h4 class="card_body">${{product.price}}</h4>
          </div>
          </div>
     </div>
    </div>
</div>
    {% empty %}
         <div class="row mx-auto">
            <p class ="text-center my_search_text">0 results found</p>
         </div>

                {% endfor %}

{% endblock %}